## Connecting to the database
spring.datasource.url=jdbc:postgresql://localhost:5433/leavedb
spring.datasource.username=postgres
spring.datasource.password=your_password

## Configuring JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=your_passoword

server.port = 8081
